### ISSUE TITLE
Transaction Summary

### ISSUE THREAD

**Issue by vishaln2it** [AuthorizeNet/accept-sdk-android#13]
Hello,
We are using the "Sample Application for the Accept Mobile Android SDK" for Credit Card transactions.
1) I am getting below response after clicking on "Fetch Token" Button.
![screenshot at 2016-12-09 13 13 40](https://cloud.githubusercontent.com/assets/13017721/21041496/5e3eba82-be11-11e6-94fe-4fe2c2190f04.png)

2) Does above response means a Successful transaction or not?

3) If Transaction is successful then where can i see Transaction Details in Website of Authorize.net .

Thanks.

**Comment by kikmak42** [comment]
Hi @vishaln2it 

This Accept sample just get the Accept token, after getting this token you need to make an API call to Authorize.net for creating a transaction.

You need to make this API call with the token you got : http://developer.authorize.net/api/reference/index.html#mobile-inapp-transactions-create-an-accept-transaction
![image](https://cloud.githubusercontent.com/assets/645401/21807747/3cbc6b0c-d766-11e6-80e4-98ae0a544121.png)

**Comment by brianmc** [comment]
And the payment transaction (which @kikmak42 mentioned) should be done from your server/mobile backend.
